# This is a basic workflow to help you get started with Actions

name: DoccanoInit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 1. New setup job to check runner availability
  check_runner:
    runs-on: ubuntu-latest
    outputs:
      active_runner: ${{ steps.check.outputs.use-runner }}
    steps:
      - name: Check if runner-grid is online
        id: check
        # Using the actively maintained fork
        uses: mikehardy/runner-fallback-action@v1
        with:
          primary-runner: "self-hosted, runner-grid"
          fallback-runner: "ubuntu-latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
  # This workflow contains a single job called "build"
  build:
    needs: check_runner
    runs-on: ${{ fromJSON(needs.check_runner.outputs.active_runner) }}
    
    container:
      image: ubuntu:22.04
      options: --user root

    services:
      doccano:
        image: doccano/doccano
        env:
            # Doccano Initialization Variables
            ADMIN_USERNAME: admin
            ADMIN_EMAIL: julia_jackson@gmail.com
            ADMIN_PASSWORD: password
            PORT: 6379
            RABBITMQ_DEFAULT_USER: doccano
            RABBITMQ_DEFAULT_PASS: doccano
            POSTGRES_USER: doccano
            POSTGRES_PASSWORD: doccano
            POSTGRES_DB: doccano
        ports:
          - 6379:6379

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Add in Docker Tools
        run: sh ./scripts/docker_install.sh
      - name: Run Doccano Ping Test
        run: sh ./scripts/doccano_ping.sh
      - name: Install julia
        run: sh ./scripts/julia_install.sh
      - name: Run Doccano Login Test
        run: sh ./scripts/doccano_login.sh
      - name: Run Full Doccano Endpoint Test
        run: sh ./scripts/doccano_full_test.sh
