# This is a basic workflow to help you get started with Actions

name: DoccanoInit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --user root

    services:
      doccano:
        image: doccano/doccano
        env:
            ADMIN_USERNAME: admin
            ADMIN_EMAIL: julia_jackson@gmail.com
            ADMIN_PASSWORD: password
            PORT: 6379
        ports:
          - 6379:6379

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Doccano
        run: sh ./scripts/doccano_install.sh
      - name: Run Doccano Ping Test
        run: sh ./scripts/doccano_ping.sh
      - name: Install julia
        run: sh ./scripts/julia_install.sh
      - name: Run Doccano Login Test
        run: sh ./scripts/doccano_login.sh
        
      - name: Curl Test
        run: |
            apt-get update; apt-get install curl wget -y
            curl doccano:6379
            wget -qO- doccano:6379 | xargs echo
            PUBLIC_IP=`wget doccano:6379 -O - -q ; echo`
            echo $PUBLIC_IP
